# This is a basic workflow to help you get started with Actions

name: Image Hunter 

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the "main" branch
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:// Sample Portfolio Data (Replace with your work)
const portfolioItems = [
    { 
        id: 1, 
        category: "logo", 
        img: "logo-design-1.jpg", 
        title: "Minimal Logo Design" 
    },
    { 
        id: 2, 
        category: "branding", 
        img: "branding-1.jpg", 
        title: "Coffee Brand Identity" 
    },
    { 
        id: 3, 
        category: "photo", 
        img: "photo-edit-1.jpg", 
        title: "Product Retouching" 
    },
    // Add more items...
];

// Load Portfolio Items
function loadPortfolio(filter = "all") {
    const gallery = document.querySelector(".gallery");
    gallery.innerHTML = "";

    const filteredItems = filter === "all" 
        ? portfolioItems 
        : portfolioItems.filter(item => item.category === filter);

    filteredItems.forEach(item => {
        const itemElement = document.createElement("div");
        itemElement.className = "gallery-item";
        itemElement.setAttribute("data-category", item.category);
        itemElement.innerHTML = `
            <img src="assets/${item.img}" alt="${item.title}">
            <div class="overlay">
                <h3>${item.title}</h3>
            </div>
        `;
        gallery.appendChild(itemElement);
    });
}

// Filter Buttons
document.querySelectorAll(".btn").forEach(button => {
    button.addEventListener("click", () => {
        document.querySelector(".btn.active").classList.remove("active");
        button.classList.add("active");
        const filter = button.getAttribute("data-filter");
        loadPortfolio(filter);
    });
});

// Initialize
loadPortfolio();
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v4

      # Runs a single command using the runners shell
      - name: Run a one-line script
        run: echo Hello, world!

      # Runs a set of commands using the runners shell
      - name: Run a multi-line script
        run: |
          echo Add other actions to build,
          echo test, and deploy your project.
